version: '3.9'

services:
  db: 
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker 
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: ms_users
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - my-network
  
  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - my-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - my-network

  msuser:
    image: msuser-0.0.1-snapshot
    restart: always
    build: ../msUser
    working_dir: /msUser
    environment:
      TZ: Ameria/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/ms_users?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: root
      SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092
    ports:
      - 8081:8081
    command: mvn spring-boot:run
    depends_on:
      - db
      - kafka
    networks:
      - my-network

  kafkaconsumer:
    image: kafkaconsumer-0.0.1-snapshot
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
