spring:
  application:
    name: testes
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/starwars?useTimezone=true&serverTimezone=UTC
    username: dev
    password: 963258
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show_sql: false