spring:
  application:
    name: msclientes

server:
  port: 0  # porta randomica, só acho que teria de ter um range

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # eureka server
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}